### PR TITLE
Add .wav && change dir structure

### LINKED ISSUE #9: All sounds should be in .wav format
This way I can submodule this repo, and it'll still compile on every system. Otherwise I have to pull these into my repo, convert them to .wav, and then commit them. Or I have to add a dependency for software that will convert these into .wav. Neither option seems like the best way to do it.

http://superuser.com/a/553509

### PR DESCRIPTION
**Pull request by GrayHatter**
closes #9

### CODE REVIEW

**Comment by GrayHatter** [comment]
@Zer0-One

**Comment by RowenStipe** [comment]
Thank you for the file conversion.

**Comment by Zer0-One** [comment]
@GrayHatter  would you mind telling me how you did the conversion?

**Comment by GrayHatter** [comment]
@Zer0-One sorry hackers secret! I just can't...

**Comment by GrayHatter** [comment]
`for f in */*.flac; do ffmpeg -i "$f" "${f%.flac}.wav"; done`

**Comment by Zer0-One** [comment]
@GrayHatter why do all of the isotoxin filenames have "isotoxin_" behind them? also, there are misspellings in a bunch of the filenames

**Comment by RowenStipe** [comment]
@Zer0-One isotoxin never got an update to the new pack structure and file names. Mine was the only one that got that update.

**Comment by Zer0-One** [comment]
@GrayHatter can you do us the honors :smile:

**Comment by GrayHatter** [comment]
sure, what's your user:pass?

**Comment by Zer0-One** [comment]
@GrayHatter the honor of _fixing the errors_, not merging the PR :unamused:

**Comment by Zer0-One** [comment]
@GrayHatter are you going to fix this anytime soon, or should I do it myself?

**Comment by GrayHatter** [comment]
@Zer0-One all yours?

**Comment by Zer0-One** [comment]
gee, thanks :unamused:

**Pull request closed without merging**
